version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --global yarn
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync public s3://$S3_BUCKET --delete
      # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"